# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: c9cbd72913fb54f73ae56a958793b8493505000b  # frozen: v1.56.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
