# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: dafe42560ace053a00e5902931972ba9f28b7d5c  # frozen: v1.32.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
